- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: "2 months"
    TRAINER: "Manohar Anaganti"
  tasks:
  - name: display course details
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"
