- name: conditions
  hosts: local
  connection: local
  vars:
    number: 13

  tasks:
  - name: check if number is less than 10
    ansible.builtin.debug:
      msg: "The number {{ number }} is less tha 10"
    when: number < 10