- name: loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - { name: "nginx", state: "absent" }
    - mysql